name: Docker WorkFlow

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  # Job to build the application
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout code
      - uses: actions/checkout@v3
      
      # Set up JDK
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # Execute Gradle build
      - name: Execute Gradle build
        run: |
          chmod +x ./gradlew
          ./gradlew build

      # Copy the JAR file to a standard name
      - name: Copy Jar file
        run: mv ./build/libs/*.jar ./app.jar

      # Upload the artifact for the next job
      - uses: actions/upload-artifact@v3
        with:
          name: job-dependencies
          path: |
            Dockerfile
            app.jar

  # Job to build and push the Docker image
  build-image:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Download the artifact from the previous job
      - uses: actions/download-artifact@v3
        with:
          name: job-dependencies
          path: .

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to DockerHub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
 
      # Build and push the Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: mishkafloof/sutton-wopro-service:${{ github.sha }}
